*** Settings ***
Documentation    Valida o popup de 2ª via da fatura (habilitação progressiva dos
...              campos Ano/Mês/Gerar) e as abas Pagamento e Consumo da tela gerada.
Library            ../../../load_env.py
Resource    ../../keywords/app-mobile-keywords.resource
Test Teardown    FECHAR APLICATIVO

*** Variables ***
${ANO_TESTE}     2026
${MES_TESTE}     Maio

*** Test Cases ***
POPUP DE SEGUNDA VIA HABILITA CAMPOS NA ORDEM CORRETA
    ABRIR APLICATIVO EVOLUA
    ACEITAR PERMISSAO DE NOTIFICACAO SE APARECER
    IR PARA TELA DE LOGIN
    FAZER LOGIN    %{EMAIL_APP_MOBILE}    %{PASSWORD_APP_MOBILE}
    CONCLUIR LOGIN E AGUARDAR HOME
    ABRIR POPUP SEGUNDA VIA
    VALIDAR ESTADO INICIAL DO POPUP
    SELECIONAR ANO    ${ANO_TESTE}
    VALIDAR MES HABILITADO E BOTAO AINDA DESABILITADO
    SELECIONAR MES    ${MES_TESTE}
    VALIDAR BOTAO GERAR HABILITADO

SEGUNDA VIA MOSTRA ABAS PAGAMENTO E CONSUMO COM DADOS VALIDOS
    ABRIR APLICATIVO EVOLUA
    ACEITAR PERMISSAO DE NOTIFICACAO SE APARECER
    IR PARA TELA DE LOGIN
    FAZER LOGIN    %{EMAIL_APP_MOBILE}    %{PASSWORD_APP_MOBILE}
    CONCLUIR LOGIN E AGUARDAR HOME
    ABRIR POPUP SEGUNDA VIA
    SELECIONAR ANO    ${ANO_TESTE}
    SELECIONAR MES    ${MES_TESTE}
    CLICAR EM GERAR SEGUNDA VIA
    VALIDAR ABA PAGAMENTO    ${MES_TESTE}    ${ANO_TESTE}
    IR PARA ABA CONSUMO
    VALIDAR ABA CONSUMO
